if GetLocale()~="zhCN" then return end

ZygorGuidesViewer.LocaleFont = [[Fonts\ZYKai_T.ttf]]

ZygorGuidesViewer_L("Main", "zhCN", function() return {
	["name"] = "|cffffff88Z|cffffee66y|cffffdd44g|cffffcc22o|cffffbb00r |cffffaa00Guides Viewer|r",
	["name_plain"] = "Zygor 指南查看器",
	["desc"] = "Zygor Guides Viewer %s 的主要设置。|n",

	['welcome_guides'] = "已加载 %d 个指引。",

	["opt_guide"] = "选择指引：",
	["opt_guide_steps"] = "步骤：%d",
	["opt_guide_author"] = "作者：%s",
	["opt_guide_next"] = "系列中的下一个：%s",

	["opt_report"] = "报告错误步骤",
	["opt_report_desc"] = "创建包含当前显示步骤详细信息的错误报告。复制并粘贴后发送给指引作者。",

	["opt_visible"] = "显示 Zygor Guides Viewer 窗口",
	["opt_visible_desc"] = "",
	["opt_hideincombat"] = "战斗中隐藏指引",
	["opt_hideincombat_desc"] = "当屏幕空间紧张时，在战斗中隐藏所有指引窗口。",

	["opt_opacitymain"] = "透明度",
	["opt_opacitymain_desc"] = "主窗口透明度。",
	["opt_framescale"] = "缩放",
	["opt_framescale_desc"] = "可以按你的偏好调整窗口大小。",
	["opt_fontsize"] = "文字缩放",
	["opt_fontsize_desc"] = "设置首选文字大小。注意窗口缩放也会影响此项。",
	["opt_fontsecsize"] = "次级文字缩放",
	["opt_fontsecsize_desc"] = "设置次级文字大小，用于显示额外描述和备注。",
	["opt_backcolor"] = "背景颜色",
	["opt_backcolor_desc"] = "窗口背景颜色。",

	["opt_group_window"] = "窗口功能",
	["opt_miniresizeup"] = "向上扩展",
	["opt_miniresizeup_desc"] = "将窗口翻转，使其向上而不是向下扩展。适合放在屏幕底部时使用。",
	["opt_opacitymini"] = "背景透明度",
	["opt_opacitymini_desc"] = "步骤窗口背景透明度。",

	["opt_showcountsteps"] = "显示步骤：",
	["opt_showcountsteps_desc"] = "显示步骤数量。\n|cffffffaa全部|r 会在可滚动列表中显示所有步骤。\n|cffffffaa1-5|r 会将当前步骤置顶，并自动调整窗口大小，仅显示后续若干步骤。",
	["opt_showcountsteps_all"] = "全部",

	["opt_group_map"] = "路径点",
	["opt_group_map_desc"] = "这些设置控制 Zygor Guides Viewer 与地图类插件的交互方式。",
	["opt_group_map_waypointing"] = "路径点插件",
	["opt_group_map_waypointing_desc"] = "选择你希望用于 Zygor Guides Viewer 路径点处理的插件。",
	['opt_group_map_hidearrowwithguide'] = "关闭窗口时隐藏箭头",
	['opt_group_map_hidearrowwithguide_desc'] = "启用后，箭头显示将跟随指引窗口可见性。\n若希望隐藏指引时箭头仍显示，请不要勾选。",
	["opt_group_addons_internal"] = "内置路径点",
	["opt_group_addons_builtin"] = "内置路径点",
	["opt_group_addons_tomtom"] = "TomTom",
	["opt_group_addons_carbonite"] = "Carbonite",
	["opt_group_addons_cart2"] = "Cartographer 2",
	["opt_group_addons_cart3"] = "Cartographer 3",
	["opt_group_addons_metamap"] = "MetaMap",
	["opt_group_addons_none"] = "无",
	["opt_debug"] = "调试",
	["opt_debug_desc"] = "显示调试信息。",
	["opt_debugging"] = "调试设置",
	["opt_debugging_desc"] = "调试选项。",

	["opt_autoskip"] = "自动前进",
	["opt_autoskip_desc"] = "当当前步骤条件全部完成时自动跳到下一步。部分条件过于复杂的步骤仍可能需要手动跳过。",

	["opt_goalicons"] = "显示步骤行图标",
	["opt_goalicons_desc"] = "显示反映完成状态的图标。",
	["opt_goalcolorize"] = "为已完成步骤行着色",
	["opt_goalcolorize_desc"] = "完成步骤行时，将整行着为绿色。",
	["opt_goalbackprogress"] = "按完成百分比应用颜色",
	["opt_goalbackprogress_desc"] = "以未完成与完成颜色之间的过渡色显示部分完成进度。|n关闭后，目标只会显示“未完成”或“完成”两种颜色。",

	["opt_group_step"] = "步骤目标",

	["opt_goalbackcolor_desc"] = "完成颜色：",
	["opt_goalbackgrounds"] = "背景着色",
	["opt_goalbackgrounds_desc"] = "为步骤行背景着色以反映完成状态。",
	["opt_goalbackcomplete"] = "完成",
	["opt_goalbackcomplete_desc"] = "此颜色用于表示已完成目标。",
	["opt_goalbackincomplete"] = "未完成",
	["opt_goalbackincomplete_desc"] = "此颜色用于表示未完成目标。",
	["opt_goalbackimpossible"] = "无法完成",
	["opt_goalbackimpossible_desc"] = "此颜色用于表示当前无法完成的目标。",

	['opt_tooltipsbelow'] = "在行内显示额外信息",
	['opt_tooltipsbelow_desc'] = "某些步骤行的额外信息可显示为行内文本，或在鼠标悬停时以提示框显示。",

	["opt_flash_desc"] = "进度提醒：",
	["opt_goalcompletionflash"] = "目标完成时闪烁",
	["opt_goalcompletionflash_desc"] = "当单个目标完成时使用视觉“闪烁”提示。",
	["opt_goalupdateflash"] = "目标进度变化时闪烁",
	["opt_goalupdateflash_desc"] = "当单个目标有进度时使用视觉“闪烁”提示。",
	["opt_flashborder"] = "步骤完成时闪烁窗口",
	["opt_flashborder_desc"] = "每当一个步骤完成时闪烁整个窗口。",

	["opt_group_display"] = "显示",
	["opt_group_display_desc"] = "设置你希望指引如何显示。",

	["opt_group_data"] = "内置指引存储",
	["opt_group_data_desc"] = "Zygor Guides Viewer 可以在内部存储商业指引（由于暴雪政策，这些内容不能以独立插件形式分发）。",
	["opt_group_data_guide"] = "内部存储的指引：",
	["opt_group_data_guide_desc"] = "从列表中选择一个内置指引进行编辑或删除。此列表不会显示作为独立插件加载的指引。",
	["opt_group_data_del"] = "删除指引",
	["opt_group_data_del_desc"] = "从内部存储中删除所选指引。",
	["opt_group_data_edit"] = "编辑指引",
	["opt_group_data_edit_desc"] = "将所选指引加载到下方编辑器窗口以进行手动修改。",
	["opt_group_data_entry"] = "指引数据：",
	["opt_group_data_entry_desc"] = "在此粘贴新指引（请记得将步骤包裹在：|nguide 指引标题|nsteps...|nsteps...|nend\n）；注意粘贴并解析较大指引（>30kB）可能需要几秒钟。",

	['opt_windowlocked'] = "锁定窗口",
	['opt_windowlocked_desc'] = "锁定窗口，使其不再响应鼠标交互。\n仅按钮仍可使用。",
	['opt_hideborder'] = "自动隐藏边框",
	['opt_hideborder_desc'] = "当鼠标离开窗口时自动隐藏窗口边框和按钮。\n将鼠标悬停在窗口标题片刻可再次显示。",

	['opt_skin'] = "窗口皮肤颜色",
	['opt_skin_desc'] = "选择窗口装饰颜色以匹配你的界面。",
	['opt_skin_violet'] = "|cffee55ff紫色",
	['opt_skin_green'] = "|cff88ff88绿色",
	['opt_skin_blue'] = "|cff99aaff蓝色",
	['opt_skin_orange'] = "|cffffbb00橙色",

	['opt_backopacity'] = "背景透明度",
	['opt_backopacity_desc'] = "窗口背景透明度。",

	["report_title"] = "按 Ctrl+C 复制此报告。|n然后将其发送给 |cffffffff%s|r 的作者，|n地址：|cffffffff%s|r。",
	["report_notitle"] = "|cffff8888（未命名指引？）|r",
	["report_noauthor"] = "|cffff8888（无可用地址）|r",

	["opt_mapbutton"] = "显示小地图按钮",
	["opt_mapbutton_desc"] = "在小地图旁显示 Zygor Guides Viewer 按钮",

	["minimap_tooltip"] = "|cffeedd99左键|r 切换指引窗口|n|cffeedd99右键|r 打开设置|n",

	["waypointaddon_set"] = "已选择路径点插件：%s",
	["waypointaddon_connecting"] = "正在连接路径点插件：%s",
	["waypointaddon_connected"] = "已成功连接到 %s。",
	["waypointaddon_fail"] = "连接 %s 失败。",
	['waypoint_step'] = "步骤 %s",

	["checkmap"] = "请查看地图。",

	["initialized"] = "初始化完成。",

	["miniframe_notloaded"] = "未加载任何升级指引。|n|n请前往 http://zygorguides.com 购买 Zygor 的 1-80 升级指引，或加载第三方指引。|n|n如果你确定已经安装了指引，请联系其作者获取安装排错帮助。",
	["miniframe_notselected"] = "当前未选择任何指引。\n请点击上方闪烁按钮以选择一个指引。",
	["miniframe_loading"] = "正在加载指引：%d%%",

	['frame_locked'] = "窗口已锁定",
	['frame_unlock'] = "|cffeedd99左键|r 解锁",
	['frame_unlocked'] = "窗口未锁定",
	['frame_lock'] = "|cffeedd99左键|r 锁定",
	['frame_settings'] = "设置",
	['frame_settings1'] = "|cffeedd99左键|r 打开菜单",
	['frame_settings2'] = "|cffeedd99右键|r 打开选项",
	['frame_minimized'] = "显示 |cffffffff%d|r 个步骤",
	['frame_maximized'] = "显示全部步骤",
	['frame_minimize'] = "|cffeedd99左键|r 仅显示 |cffffffff%d|r 个",
	['frame_minright'] = "|cffeedd99右键|r 设置显示步骤数",
	['frame_maximize'] = "|cffeedd99左键|r 显示全部",
	['frame_stepnav_prev'] = "上一步",
	['frame_stepnav_prev_click'] = "|cffeedd99左键|r：后退",
	['frame_stepnav_prev_right'] = "|cffeedd99右键|r：回退",
	['frame_stepnav_next'] = "下一步",
	['frame_stepnav_next_click'] = "|cffeedd99左键|r：前进",
	['frame_stepnav_next_right'] = "|cffeedd99右键|r：快速前进",
	['frame_section'] = "当前指引",
	['frame_section_click'] = "|cffeedd99点击|r 选择",

	['tooltip_tip'] = "|cff99ff00%s|r",
	['tooltip_waypoint'] = "|cffeedd99点击|r|cff00ff00 设置路径点：|cffffaa00%s|r",
	['tooltip_waypoint_coords'] = "位置：|cffffaa00%s|r",

	["message_errorloading_full"] = "加载指引 |cffaaffaa%s|r 时发生 |cffff4444错误|r\n第 %d 行：%s\n错误：%s",
	["message_errorloading_brief"] = "加载指引 |cffaaffaa%s|r 时发生 |cffff4444错误|r",
	["message_loadedguide"] = "已启用指引：|cffaaffaa%s|r",
	["message_missingguide"] = "缺失指引：|cffaaffaa%s|r",
	["title_noguide"] = "Zygor Guides Viewer（未加载指引）",

	['step_num'] = "|cffaaaaaa%s|cff888888.|r ",
	['step_level'] = "|cffaaccaa等级：|cffcceecc%s|cffaaccaa|r ",

	["questtitle"] = "“%s”",
	["questtitle_part"] = "“%s”（第 %s 部分）",
	["coords"] = "%d,%d",
	["map_coords"] = "%s %d,%d",

	["stepgoal_home"] = "将炉石地点设置为 %s",
	["stepgoal_flightpath"] = "获取 %s 飞行点",

	["stepgoal_accept"] = "接受 %s",
	["stepgoal_turn in"] = "交付 %s",
	["stepgoal_talk to"] = "与 %s 对话",
	["stepgoal_kill"] = "击杀 %s",
	["stepgoal_kill #"] = "击杀 %s %s",
	["stepgoal_goal"] = "%s",
	["stepgoal_goal #"] = "%s %s",
	["stepgoal_get"] = "获得 %s",
	["stepgoal_get #"] = "获得 %s %s",
	["stepgoal_ding"] = "你现在应为 %s 级。|n    若不是，请稍微刷怪直到达到该等级。",
	["stepgoal_go to"] = "前往 %s",
	["stepgoal_also at"] = "也在 %s",
	["stepgoal_hearth to"] = "炉石返回 %s",
	["stepgoal_collect"] = "收集 %s",
	["stepgoal_collect #"] = "收集 %s %s",
	["stepgoal_buy"] = "购买 %s %s",
	["stepgoal_fpath"] = "获取 %s 飞行点",
	["stepgoal_use"] = "使用 %s",
	["stepgoal_home"] = "将 %s 设为你的炉石地点",
	["stepgoal_petaction"] = "使用宠物技能 %s",
	["stepgoal_havebuff"] = "获得增益/减益“%s”",
	["stepgoal_nobuff"] = "失去增益/减益“%s”",
	["stepgoal_invehicle"] = "进入载具",
	["stepgoal_outvehicle"] = "离开载具",
	["stepgoal_equipped"] = "装备 %s",
	["stepgoal_at_suff"] = "（%s）",

	["completion_collect"] = "(%s/%s)",
	["completion_goal"] = "(%s/%s)",
	["completion_ding"] = "(%s%%)",
	["completion_done"] = "(完成)",
	["completion_rep"] = "(%s)",

	["step_req"] = "此步骤仅对以下条件有效：%s",

	["map_highlight"] = "高亮",

	["stepreq"] = "步骤职业/种族要求：",
	["stepreqor"] = " 或 ",

	["opt_do_searchforgoal"] = "查找可完成目标",
	["searching_for_goal_success"] = "已找到一个可完成目标：%s。它可能是你在此指引中的合适起点。",
	["searching_for_goal_failed"] = "未找到可完成目标。请尝试其他指引或章节、先接一些任务，或从章节开头再次搜索（搜索只会向前进行）。",


	["going"] = "%d%% ?? %s",
	["opt_stepnumber"] = "??????",
	["opt_stepnumber_desc"] = "???????????????\n??????????",
	["opt_hidestepborders"] = "????",
	["opt_hidestepborders_desc"] = "????????????",
	["opt_stepbackopacity"] = "?????",
	["opt_stepbackopacity_desc"] = "??????????\n???????????????????",
	["opt_goalbackprogressing"] = "????",
	["opt_goalbackprogressing_desc"] = "?????????? 50%?",
	["opt_progressbackcolor_desc"] = "?????",
	["opt_goalbackaux"] = "??",
	["opt_goalbackaux_desc"] = "??????????",
	["opt_goalbackobsolete"] = "??",
	["opt_goalbackobsolete_desc"] = "???????????????",
	["opt_resetwindow"] = "????",
	["opt_resetwindow_desc"] = "?????????????????????",
	["opt_trackchains"] = "?????",
	["opt_trackchains_desc"] = "?????????????????????????\n\n????????????????????????????????????????????????",
	["opt_guidesinhistory"] = "??????",
	["opt_guidesinhistory_desc"] = "?????????????",
	["opt_skin_remaster"] = "|cffc7d9ffRemaster????",
	["opt_group_progress"] = "????",
	["opt_group_progress_desc"] = "??????????????????????????????",
	["opt_levelsahead"] = "??????",
	["opt_levelsahead_desc"] = "?????????????????\n??? 0 ????????????????????????\n??? 1 ?????????????????????",
	["opt_showobsolete"] = "??????",
	["opt_showobsolete_desc"] = "????????????\n??????????????????",
	["opt_skipobsolete"] = "??????",
	["opt_skipobsolete_desc"] = "?????????",
	["opt_skipauxsteps"] = "??????",
	["opt_skipauxsteps_desc"] = "???????????????????????????\n????????????????????",
	["opt_skipflightsteps"] = "???????",
	["opt_skipflightsteps_desc"] = "??????????????????????????????\n\n?????????????????????",
	["opt_skipimpossible"] = "????????",
	["opt_skipimpossible_desc"] = "?????????????????????????????",
	["opt_group_progress_bottomdesc"] = "????????????????????????????????????????????????????????????\n\n?????????????????????????????????????????????????????????????????\n\n???????????????????????????????????????????????????????????",
	["opt_group_mapinternal"] = "?????",
	["opt_arrowmeters"] = "????",
	["opt_arrowmeters_desc"] = "?????????????",
	["opt_arrowfreeze"] = "??????",
	["opt_arrowfreeze_desc"] = "???????????????????",
	["opt_arrowcam"] = "??????",
	["opt_arrowcam_desc"] = "?????????????????????\n\n???????????????????????",
	["opt_arrowcolordir"] = "????",
	["opt_arrowcolordir_desc"] = "??????????????????????\n\n?????????????",
	["opt_arrowscale"] = "????",
	["opt_arrowscale_desc"] = "?????",
	["opt_arrowfontsize"] = "??????",
	["opt_arrowfontsize_desc"] = "??????????",
	["opt_minimapzoom"] = "???????",
	["opt_minimapzoom_desc"] = "??????????????????????",
	["opt_foglight"] = "??????",
	["opt_foglight_desc"] = "??????????????????????",
	["opt_group_gold"] = "????",
	["opt_group_gold_desc"] = "???????????????????",
	["opt_gold_detectiondist"] = "????",
	["opt_gold_detectiondist_desc"] = "???????????????",
	["opt_gold_reqmode"] = "????",
	["opt_gold_reqmode_desc"] = "????????????",
	["opt_gold_reqmode_all"] = "??",
	["opt_gold_reqmode_current"] = "?????",
	["opt_gold_reqmode_future"] = "?? + ????",
	["gold_missing_noguidesloaded"] = "????????",
	["gold_missing_nospotsinrange"] = "?????????????",
	["gold_header_ore"] = "???",
	["gold_header_herb"] = "???",
	["gold_header_skin"] = "??????",
	["gold_header_drop"] = "|cffffdddd%s|r ????",
	["opt_group_convenience"] = "????",
	["opt_group_convenience_desc"] = "????????????",
	["opt_autoaccept"] = "?????",
	["opt_autoaccept_desc"] = "?????????",
	["opt_autoturnin"] = "?????",
	["opt_autoturnin_desc"] = "??????????",
	["opt_fixblizzardautoaccept"] = "?????????",
	["opt_fixblizzardautoaccept_desc"] = "????????????????????/????????????",
	["opt_audiocues"] = "????",
	["opt_audiocues_desc"] = "??????????????",
	["opt_analyzereps"] = "????",
	["opt_analyzereps_desc"] = "??????????????????????????",
	["opt_mapcoords"] = "??????",
	["opt_mapcoords_desc"] = "???????????????",
	["stepgoal_rep"] = "?? %s ???%s?",
	["stepgoal_achieve"] = "?????%s?",
	["stepgoal_achievesub"] = "???%s???????%s?",
	["stepgoal_skill"] = "? %s ??? %s",
	["stepgoal_skillmax"] = "? %s ??????? %s",
	["stepgoal_learn"] = "???? %s",
	["stepgoal_or"] = "  - ? -",
	["stepgoalshort_complete"] = "??",
	["stepgoalshort_incomplete"] = "???",
	["stepgoalshort_questgoal"] = "(%d/%d)",
	["stepgoalshort_level"] = "(%d%%)",
	["waypointaddon_detecting"] = "?????????????...",
	["waypointaddon_disconnected"] = "?? |cffddeeff%s|r ?????",
	["pointer_corpselabel1"] = "????",
	["pointer_corpselabel2"] = "??????...",
	["pointer_corpselabel3"] = "???????????",
	["pointer_corpselabel4"] = "?????",
	["pointer_corpselabel5"] = "????????",
	["req_not"] = "? %s",
	["haman$"] = "hamans",
	["(%a)man$"] = "%1men",

	["binding_togglewindow"] = "显示指引窗口",
	["binding_prev"] = "上一步",
	["binding_next"] = "下一步",
	["binding_actionbutton1"] = "Action Button 1",
	["binding_actionbutton2"] = "Action Button 2",
	["binding_actionbutton3"] = "Action Button 3",
	["binding_actionbutton4"] = "Action Button 4",
	["binding_actionbutton5"] = "Action Button 5",
	["menu_last"] = "最近使用的指引：",
	["menu_last_entry"] = "%s |cffaaaaaa步骤|r %d",
	["gb_window_title"] = "Guide Browser",
	["gb_addon_title"] = "Zygor Guides Viewer Remastered",
	["gb_root"] = "Root",
	["gb_search"] = "Search",
	["gb_folders"] = "Folders",
	["gb_guides"] = "Guides",
	["gb_load_guide"] = "Load Guide",
	["gb_open_legacy"] = "Open Legacy Picker",
	["gb_path_format"] = "Path: %s",
	["gb_select_guide"] = "Select a guide",
	["gb_select_guide_from_list"] = "从列表中选择一个指南。",
	["gb_select_settings_page"] = "选择一个设置页面",
	["gb_all_guides"] = "全部指南",
	["gb_other"] = "其他",
	["gb_unknown"] = "未知",
	["gb_none"] = "无",
	["gb_folder_format"] = "文件夹：%s",
	["gb_progress_format"] = "进度：%d%%",
	["gb_guides_count_format"] = "%d 个指南",
	["gb_current_meta_format"] = "Step %d / %d  |  %s",
	["gb_detail_meta_format"] = "Steps: %d\nAuthor: %s\nNext: %s",
	["gb_tab_home"] = "主页",
	["gb_tab_featured"] = "推荐",
	["gb_tab_current"] = "当前",
	["gb_tab_recent"] = "最近",
	["gb_tab_options"] = "设置",
	["gb_cat_leveling"] = "Leveling",
	["gb_cat_dungeons"] = "Dungeons",
	["gb_cat_daily"] = "Daily",
	["gb_cat_events"] = "Events",
	["gb_cat_reputations"] = "Reputations",
	["gb_cat_gold"] = "Gold",
	["gb_cat_professions"] = "Professions",
	["gb_cat_petsmounts"] = "Pets & Mounts",
	["gb_cat_titles"] = "Titles",
	["gb_cat_achievements"] = "Achievements",
	["gb_cat_misc"] = "Misc",
	["gb_cat_favorites"] = "Favorites",
	["gb_opt_guides"] = "指南",
	["gb_opt_desc_guides"] = "指南选择、当前指南信息和核心控制。",
	["gb_opt_stepdisplay"] = "步骤显示",
	["gb_opt_desc_stepdisplay"] = "查看器外观、框体布局、皮肤/字体以及步骤与目标显示控制。",
	["gb_opt_progress"] = "进度",
	["gb_opt_desc_progress"] = "步骤推进行为、跳过规则和完成流程。",
	["gb_opt_travel"] = "旅行系统",
	["gb_opt_desc_travel"] = "路径点提供者选择和旅行系统行为。",
	["gb_opt_map"] = "地图与路径点",
	["gb_opt_desc_map"] = "箭头样式、小地图/地图标记和路径点外观。",
	["gb_opt_notifications"] = "通知",
	["gb_opt_desc_notifications"] = "进度/完成时的闪烁与提醒。",
	["gb_opt_actionbuttons"] = "动作按钮",
	["gb_opt_desc_actionbuttons"] = "可点击步骤/目标交互的显示行为。",
	["gb_opt_convenience"] = "任务",
	["gb_opt_desc_convenience"] = "自动接取/交付以及便捷任务辅助。",
	["gb_opt_accessibility"] = "无障碍",
	["gb_opt_desc_accessibility"] = "提升颜色可见性和可读性的选项。",
	["gb_opt_profile"] = "配置档",
	["gb_opt_desc_profile"] = "按角色/全局配置档管理以及复制/重置工具。",
	["gb_opt_about"] = "关于",
	["gb_opt_desc_about"] = "版本、支持和诊断/报错工具。",
	["gb_opt_advanced"] = "高级",
	["gb_opt_desc_advanced"] = "调试工具、诊断和开发者控制。",
	["gb_opt_general"] = "常规",
	["gb_opt_desc_general"] = "常规设置。",
	["gb_title_viewer"] = "查看器",
	["gb_options_viewer_desc"] = "查看器核心行为、指南加载和基础插件控制。",
	["gb_hint_search_settings"] = "提示：\n使用左侧搜索可快速找到设置页面。",
	["gb_hint_options_filter"] = "提示：\n左侧搜索会筛选设置页面。\n使用“打开完整选项”查看完整的 Blizzard 面板。",
	["gb_empty_no_guides_search"] = "没有指南匹配此搜索。",
	["gb_empty_no_guides_category"] = "此分类中没有指南。",
	["gb_empty_no_current_guide"] = "当前没有加载指南。",
	["gb_empty_no_current_guide_short"] = "当前没有加载指南",
	["gb_empty_no_recent_guides"] = "还没有最近使用的指南。",
	["gb_empty_no_featured_match"] = "没有推荐项符合此筛选。",
	["gb_empty_no_featured_suggestions"] = "没有推荐建议",
	["gb_empty_no_favorites"] = "还没有收藏的指南。",
	["gb_no_guide_selected"] = "未选择指南",
	["gb_action_clear_search"] = "Clear search",
	["gb_action_show_all_categories"] = "Show all categories",
	["gb_action_go_home"] = "Go to Home",
	["gb_action_open_home"] = "Open Home",
	["gb_action_reset_snoozed"] = "Reset snoozed suggestions",
	["gb_action_clear_search_restore"] = "Clear search to restore suggestions",
	["gb_action_reset_snoozed_restore"] = "Reset snoozed suggestions to restore recommendations",
	["gb_action_try_home"] = "Try Home to browse all categories",
	["gb_action_browse_all_from_home"] = "Browse all guides from Home",
	["gb_action_back_to_guides"] = "Back to Guides",
	["gb_action_open_full_options"] = "Open Full Options",
	["gb_action_go_current_folder"] = "Go to Current Guide Folder",
	["gb_action_resume"] = "Resume",
	["gb_action_restart"] = "Restart",
	["gb_nav_navigation"] = "Navigation",
	["gb_nav_back"] = "Back",
	["gb_nav_reset_to_root"] = "Reset to Category Root",
	["gb_featured_bucket_next"] = "Next Up",
	["gb_featured_bucket_progress"] = "In Progress",
	["gb_featured_bucket_level"] = "Around Your Level",
	["gb_featured_bucket_featured"] = "Featured Routes",
	["gb_featured_confidence_strong"] = "Strong",
	["gb_featured_confidence_good"] = "Good",
	["gb_featured_confidence_fallback"] = "Fallback",
	["gb_roadmap"] = "Roadmap",
	["gb_roadmap_bucket_format"] = "%s Roadmap",
	["gb_bucket_preview_next_with_title"] = "Continue your chain: %s",
	["gb_bucket_preview_next"] = "Continue your chain",
	["gb_bucket_preview_progress_with_title"] = "Resume: %s",
	["gb_bucket_preview_progress"] = "Resume in-progress guides",
	["gb_bucket_preview_level_with_title"] = "Start level-fit: %s",
	["gb_bucket_preview_level"] = "Start level-fit guides",
	["gb_bucket_preview_featured_with_title"] = "Optional route: %s",
	["gb_bucket_preview_featured"] = "Optional routes and extras",
	["gb_meta_action"] = "Action",
	["gb_meta_suggestion"] = "Suggestion",
	["gb_meta_suggested"] = "Suggested",
	["gb_meta_current"] = "Current",
	["gb_meta_recommended"] = "recommended",
	["gb_meta_other_useful_option"] = "other useful option",
	["gb_meta_current_selection"] = "current selection",
	["gb_meta_suggestions_snoozed"] = "suggestions may be snoozed",
	["gb_meta_restore_recommendations"] = "restore recommendations",
	["gb_meta_filter_no_matches"] = "filter has no matches",
	["gb_meta_see_full_recommendations"] = "see full recommendations",
	["gb_meta_no_bucket_suggestions"] = "no suggestions in this bucket",
	["gb_meta_full_category_access"] = "full category access",
	["gb_meta_suggested_from"] = "Suggested from: %s",
	["gb_meta_confidence"] = "Confidence: %s",
	["gb_meta_why_prefix"] = "Why: ",
	["gb_meta_gain_prefix"] = "Gain: ",
	["gb_reason_recently_used"] = "recently used",
	["gb_reason_incomplete"] = "incomplete",
	["gb_reason_your_level_range"] = "your level range",
	["gb_reason_near_your_level"] = "near your level",
	["gb_reason_your_class"] = "your class",
	["gb_reason_your_race"] = "your race",
	["gb_reason_your_profession"] = "your profession",
	["gb_reason_favorite"] = "favorite",
	["gb_reason_current_chain"] = "current chain",
	["gb_reason_chain_step_format"] = "chain step +%d",
	["gb_reason_inferred_continuation"] = "inferred continuation",
	["gb_reason_chapter_continuation"] = "chapter continuation",
	["gb_tooltip_featured_controls"] = "Featured suggestion controls",
	["gb_tooltip_featured_click"] = "Click the X: snooze for 24 hours",
	["gb_tooltip_featured_shift_click"] = "Shift-click X: hide for this session",
	["gb_tooltip_featured_restore"] = "Press R or use reset in options to restore.",
	["gb_tooltip_snooze"] = "Snooze suggestion",
	["gb_tooltip_snooze_click"] = "Click: hide for 24 hours",
	["gb_tooltip_snooze_shift_click"] = "Shift-click: hide for this session",
	["gb_tooltip_why_prefix"] = "Why: ",
	["gb_tooltip_gain_prefix"] = "Gain: ",
	["gb_tooltip_confidence_prefix"] = "Confidence: ",
	["gb_tooltip_chain_prefix"] = "Chain: ",
	["gb_tooltip_fallback_recommendation"] = "Fallback recommendation",
	["gb_current_guide"] = "当前指南",
	["gb_options_fallback_embed_unavailable"] = "内嵌选项不可用。再次点击“设置”以打开 Blizzard 界面选项。",
	["gb_options_fallback_missing_widgets"] = "内嵌选项不可用。缺少 AceGUI 嵌入控件。",
	["gb_options_fallback_render_error"] = "无法渲染内嵌选项：%s",
	["opt_legacyguideddropdown"] = "旧版指南下拉菜单",
	["opt_featured_header"] = "精选推荐",
	["opt_featured_enablefallback"] = "启用备用推荐",
	["opt_featured_enablefallback_desc"] = "当精选分组没有直接匹配时，显示一些有用的备用指南。",
	["opt_featured_hiderecentcompleted"] = "隐藏最近完成的指南",
	["opt_featured_hiderecentcompleted_desc"] = "将刚刚完成的指南从智能精选推荐中隐藏。",
	["opt_featured_showconfidence"] = "显示置信标签",
	["opt_featured_showconfidence_desc"] = "在精选条目中显示 Strong/Good/Fallback 置信标记。",
	["opt_featured_resethidden"] = "重置已隐藏推荐",
	["opt_featured_resethidden_desc"] = "恢复通过关闭按钮隐藏的精选推荐。",
	["opt_disablerouteloopstacking"] = "禁用路线/循环堆叠",
	["opt_disablerouteloopstacking_desc"] = "防止路线和循环内容堆叠到同一个精选分组中。",
	["opt_accessibility_intro"] = "调整颜色可见性和文字清晰度相关的视觉无障碍选项。",
	["opt_colorblindmode"] = "色盲模式",
	["opt_colorblindmode_desc"] = "将指南、箭头和距离颜色替换为适合色盲的调色板，同时强制使用更高对比度的箭头名词颜色。",
	["opt_colorblindmode_off"] = "关闭",
	["opt_colorblindmode_protanopia"] = "红色盲",
	["opt_colorblindmode_deuteranopia"] = "绿色盲",
	["opt_colorblindmode_tritanopia"] = "蓝色盲",
	["opt_colorblindmode_global"] = "全局",
	["opt_colorblindmode_custom"] = "自定义",
	["opt_arrowcolor_far"] = "远",
	["opt_arrowcolor_mid"] = "中",
	["opt_arrowcolor_near"] = "近",
	["opt_simplifyarrownouncolors"] = "简化箭头文字颜色",
	["opt_simplifyarrownouncolors_desc"] = "为箭头标签使用更清晰、更高对比度的颜色。",
	["opt_about_heading"] = "适用于 WoTLK 3.3.5a 的 Zygor Guides Viewer Remastered",
	["opt_about_support"] = "支持",
	["opt_about_diag"] = "提示：`/zygor status` 和 `/zygor debug` 可帮助排查问题。",
	["opt_showminimapicons"] = "显示小地图图标",
	["opt_showminimapicons_desc"] = "在小地图上显示图标",
	["opt_iconalpha"] = "图标透明度",
	["opt_iconalpha_desc"] = "地图标记图标的透明度",
	["opt_iconsize"] = "图标大小",
	["opt_iconsize_desc"] = "地图上图标的大小",
	["opt_arrowshow"] = "显示箭头",
	["opt_arrowshow_desc"] = "显示或隐藏内置路径点箭头。",
	["opt_arrowcolormode_direction"] = "方向",
	["opt_arrowcolormode_distance"] = "距离",
	["opt_arrowtextoutline"] = "箭头文字描边",
	["opt_arrowtextoutline_desc"] = "选择路径点箭头文字的描边强度。",
	["opt_arrowtextoutline_default"] = "默认",
	["opt_arrowtextoutline_strong"] = "强",
	["opt_arrowtextoutline_reduced"] = "弱",
	["opt_remasterpointeronlegacy"] = "在旧皮肤上使用重制版指针",
	["opt_remasterpointeronlegacy_desc"] = "启用后，旧皮肤将使用重制版路径点箭头样式。",
	["opt_resetarrowposition"] = "重置箭头位置",
	["opt_resetarrowposition_desc"] = "将路径点箭头重置为默认位置。",
	["opt_foglightdebug"] = "（调试）检查 foglight",
	["opt_foglightdebug_desc"] = "检查当前地图的 foglight",
	["opt_travelsystem_intro"] = "选择如何处理旅行和路径点提供者。",
	["opt_mapswaypoints_intro"] = "配置地图标记和内置箭头外观。",
	["opt_notifications_intro"] = "配置步骤推进时的视觉通知提示。",
	["opt_actionbuttons_intro"] = "配置目标图标和交互式步骤显示。",
	["opt_actionbar_enable"] = "Enable Action Bar",
	["opt_actionbar_enable_desc"] = "Show a movable action bar for the current step's actionable goals.",
	["opt_actionbar_onlywhenneeded"] = "Show Only When Needed",
	["opt_actionbar_onlywhenneeded_desc"] = "Hide the action bar when the current step has no actionable buttons.",
	["opt_actionbar_locked"] = "Lock Action Bar Position",
	["opt_actionbar_locked_desc"] = "Prevent the action bar from being dragged.",
	["opt_actionbar_scale"] = "Action Bar Scale",
	["opt_actionbar_scale_desc"] = "Scale of the action bar.",
	["opt_actionbar_size"] = "Button Size",
	["opt_actionbar_size_desc"] = "Size of each action bar button.",
	["opt_actionbar_spacing"] = "Button Spacing",
	["opt_actionbar_spacing_desc"] = "Spacing between action bar buttons.",
	["opt_actionbar_pinside"] = "Pinned Side",
	["opt_actionbar_pinside_desc"] = "Choose which side of the viewer the snapped action bar should attach to.",
	["opt_actionbar_pinside_top"] = "Top",
	["opt_actionbar_pinside_bottom"] = "Bottom",
	["opt_actionbar_pinside_left"] = "Left",
	["opt_actionbar_pinside_right"] = "Right",
	["opt_actionbar_resetanchor"] = "Reset Action Bar Position",
	["opt_actionbar_resetanchor_desc"] = "Reset the action bar to its default snapped position.",
	["opt_actionbar_markers"] = "Enable Target Markers",
	["opt_actionbar_markers_desc"] = "Attempt to place raid target markers on talk and kill targets when possible.",
	["opt_targetpreview_header"] = "Target Preview",
	["opt_targetpreview_intro"] = "Show a movable preview pane for the current talk or kill target.",
	["opt_targetpreview_enable"] = "Enable Target Preview",
	["opt_targetpreview_enable_desc"] = "Show a movable preview pane for the current step's talk and kill targets.",
	["opt_targetpreview_onlywhenneeded"] = "Show Only When Relevant",
	["opt_targetpreview_onlywhenneeded_desc"] = "Hide the preview pane when the current step has no talk or kill target to preview.",
	["opt_targetpreview_locked"] = "Lock Preview Position",
	["opt_targetpreview_locked_desc"] = "Prevent the target preview pane from being dragged.",
	["opt_targetpreview_scale"] = "Preview Scale",
	["opt_targetpreview_scale_desc"] = "Scale of the target preview pane.",
	["opt_targetpreview_width"] = "Preview Width",
	["opt_targetpreview_width_desc"] = "Width of the target preview pane.",
	["opt_targetpreview_height"] = "Preview Height",
	["opt_targetpreview_height_desc"] = "Height of the target preview pane.",
	["opt_targetpreview_pinside"] = "Pinned Side",
	["opt_targetpreview_pinside_desc"] = "Choose which side of the viewer the snapped target preview should attach to.",
	["opt_targetpreview_mode"] = "Preview Mode",
	["opt_targetpreview_mode_desc"] = "Choose whether the preview prefers a live 3D model, a styled info card, or both.",
	["opt_targetpreview_mode_hybrid"] = "Hybrid",
	["opt_targetpreview_mode_model"] = "3D Only",
	["opt_targetpreview_mode_card"] = "Info Card Only",
	["opt_targetpreview_resetanchor"] = "Reset Target Preview Position",
	["opt_targetpreview_resetanchor_desc"] = "Reset the target preview pane to its default snapped position.",
	["targetpreview_title"] = "Drag to move Target Preview",
	["targetpreview_title_locked"] = "Target Preview",
	["targetpreview_role_talk"] = "Talk to",
	["targetpreview_role_kill"] = "Kill",
	["targetpreview_hint"] = "Target this creature to preview its 3D model.",
	["targetpreview_hint_empty"] = "No talk or kill target is active on this step.",
	["targetpreview_empty_name"] = "No Target",
	["actionbutton_bar_title"] = "Drag to move Action Buttons",
	["actionbutton_bar_title_locked"] = "Action Buttons",
	["actionbutton_tooltip_talk"] = "Target %s and try to mark it with a green triangle.",
	["actionbutton_tooltip_kill"] = "Target %s and try to mark it with a skull.",
	["actionbutton_tooltip_script"] = "Run the current step script macro.",
	["actionbutton_tooltip_petaction"] = "Use the suggested pet action.",
	["frame_toolbar_guides"] = "指南",
	["frame_toolbar_guides_click"] = "打开指南菜单",
	["frame_toolbar_guides_right"] = "打开指南管理器",
	["frame_toolbar_close"] = "关闭",
	["frame_toolbar_close_click"] = "关闭",
	["frame_toolbar_settings"] = "设置",
	["frame_toolbar_settings_click"] = "打开快捷菜单",
	["frame_toolbar_settings_right"] = "打开指南管理器设置",
	["frame_toolbar_stepview"] = "步骤视图",
	["frame_toolbar_stepview_showall"] = "显示全部",
	["frame_toolbar_stepview_showonly"] = "仅显示 |cffffffff%s|r",
	["frame_toolbar_stepview_setcount"] = "设置步骤数量",
	["frame_toolbar_unlock"] = "解锁窗口",
	["frame_toolbar_unlock_click"] = "解锁",
	["frame_toolbar_lock"] = "锁定窗口",
	["frame_toolbar_lock_click"] = "锁定",
	["frame_title_default"] = "Zygor Guides",
	["frame_tab_guides"] = "指南",
	["frame_tab_spots"] = "点位",
} end)

local plurals = {
}

ZygorGuidesViewer_L("Specials", "zhCN", function() return {
	["plural"] = function (word)
		return word
	end,
	['contract_mobs'] = false,
	['contract_mobs_old'] = function(mobs)
			local start,ending

			if not mobs[1].name and type(mobs)=="table" then
				local l=mobs
				mobs={}
				for i=1,#l do mobs[i]={name=l[i]} end
			end
			local common,all
			for i=1,50 do
				common = mobs[1].name:sub(1,i)
				all=true
				for m=2,#mobs do
					if mobs[m].name:find(common)~=1 then
						all=false
						break
					end
				end
				if not all then
					common = common:sub(1,-2)
					break
				end
			end
			if common:sub(-1)==" " then common = common:sub(1,-2) end
			start=common

			for i=1,50 do
				common = mobs[1].name:sub(-i)
				all=true
				for m=2,#mobs do
					if mobs[m].name:sub(-i)~=common then
						all=false
						break
					end
				end
				if not all then
					common = common:sub(2)
					break
				end
			end
			if common:sub(1,1)==" " then common = common:sub(2) end
			ending=common

			if #start>#ending and #start>3 then
				return ZygorGuidesViewer_L("Specials")['contract_mobs_start'](start)
			elseif #ending>#start and #ending>3 then
				return ZygorGuidesViewer_L("Specials")['contract_mobs_end'](ending)
			else
				return nil
			end
		end,
	['contract_mobs_start'] = function(s) return ZygorGuidesViewer_L("Specials")['plural'](s) end,
	['contract_mobs_end'] = function(s)
		return ZygorGuidesViewer_L("Specials")['plural'](s)
	end,
} end)

ZygorGuidesViewer_L("G_string", "zhCN", function() return {
} end)
